table inet sovereign{
  chain input{type filter hook input priority 0; policy drop;
    iif "lo" accept; ct state established,related accept;
    tcp dport {22,80,443,8443} ct state new limit rate 10/min accept;
    log prefix "SOVEREIGN_DROP: "}
  chain forward{type filter hook forward priority 0; policy drop;}
  chain output {type filter hook output  priority 0; policy accept;}}
